#!/usr/bin/env bash

search_paths=(
    "$HOME/dotfiles:0:0"
    "$HOME/workspace:1:1"
)

results=()

for entry in "${search_paths[@]}"; do
    IFS=':' read -r path mindepth maxdepth <<<"$entry"
    while IFS= read -r dir; do
        results+=("$dir")
    done < <(find "$path" -mindepth "$mindepth" -maxdepth "$maxdepth" -type d)
done

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(printf "%s\n" "${results[@]}" | sed "s|$HOME|~|" | fzf --preview="")
    selected=${selected/#\~/$HOME}
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if [[ -n $TMUX ]]; then
    tmux new-session -d -s "$selected_name" -c "$selected"
    tmux switch-client -t "$selected_name"
else
    tmux new-session -A -s "$selected_name" -c "$selected"
fi
