#!/usr/bin/env bash

VOLUME=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2 * 100)}')
MUTED=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -c MUTED)

if [[ $MUTED -eq 1 ]]; then
    ICON="󰝟"
elif [ "$VOLUME" -eq 0 ]; then
    ICON="󰕿"
elif [ "$VOLUME" -lt 20 ]; then
    ICON="󰖀"
elif [ "$VOLUME" -lt 60 ]; then
    ICON="󰖀"
else
    ICON="󰕾"
fi

notify-send -e -h string:x-canonical-private-synchronous:volume -h "int:value:${VOLUME}" -t 800 "${ICON} ${VOLUME}%"
