return {
    'folke/which-key.nvim',
    event = { 'BufReadPost', 'BufNewFile' },
    keys = '<leader>',
    opts = {
        icons = {
            mappings = vim.g.have_nerd_font,
            keys = vim.g.have_nerd_font and {} or {
                Up = '<Up> ',
                Down = '<Down> ',
                Left = '<Left> ',
                Right = '<Right> ',
                C = '<C-…> ',
                M = '<M-…> ',
                D = '<D-…> ',
                S = '<S-…> ',
                CR = '<CR> ',
                Esc = '<Esc> ',
                ScrollWheelDown = '<ScrollWheelDown> ',
                ScrollWheelUp = '<ScrollWheelUp> ',
                NL = '<NL> ',
                BS = '<BS> ',
                Space = '<Space> ',
                Tab = '<Tab> ',
                F1 = '<F1>',
                F2 = '<F2>',
                F3 = '<F3>',
                F4 = '<F4>',
                F5 = '<F5>',
                F6 = '<F6>',
                F7 = '<F7>',
                F8 = '<F8>',
                F9 = '<F9>',
                F10 = '<F10>',
                F11 = '<F11>',
                F12 = '<F12>',
            },
        },

        spec = {
            { '<leader>c', group = 'Code', mode = { 'n', 'x' } },
            { '<leader>d', group = 'Document', mode = { 'n' } },
            { '<leader>r', group = 'Rename', mode = { 'n' } },
            { '<leader>s', group = 'Picker', mode = { 'n' } },
            { '<leader>w', group = 'Workspace', mode = { 'n' } },
            { '<leader>t', group = 'Vtsls', mode = { 'n' } },
            { '<leader>l', group = 'LazyGit', mode = { 'n' } },
            { '<leader>z', group = 'ZenMode', mode = { 'n' } },
            { '<leader>h', group = 'Git Hunk', mode = { 'n', 'v' } },
            { '<leader>b', group = 'Buffers', mode = { 'n' } },
        },

        win = {
            border = 'single',
        },
    },
}
