#!/usr/bin/env bash

search_paths=(
    "$HOME/dotfiles:0:0"
    "$HOME/workspace:1:1"
)

results=()

for entry in "${search_paths[@]}"; do
    IFS=':' read -r path mindepth maxdepth <<<"$entry"
    while IFS= read -r dir; do
        results+=("$dir")
    done < <(find "$path" -mindepth "$mindepth" -maxdepth "$maxdepth" -type d)
done

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(printf "%s\n" "${results[@]}" | fzf --preview="" --margin=6)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z $TMUX ]]; then
    tmux attach -t "$selected_name"
else
    tmux switch-client -t "$selected_name"
fi
