{
  imports = [
    ./git.nix
    ./nvim.nix
    ./spicetify.nix
    ./yazi.nix
    ./btop.nix
    ./zsh.nix
    ./scripts/default.nix
    ./fastfetch.nix
    ./hyprland/default.nix
    ./wezterm.nix
    ./dunst.nix
    ./rofi.nix
    ../stylix.nix
    ./stylix-themes.nix
    ./browser.nix
    ./zoxide.nix
    ./aichat.nix
    ./ssh.nix
    ./fzf.nix
  ];
}
