#!/usr/bin/env bash
#
# script name: dm-wifi
# Description: Connect to wifi using dmenu
# Dependencies: dmenu, fzf, rofi, nmcli, Any Nerd Font
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributor: WitherCubes, Derek Taylor

set -euo pipefail

# shellcheck disable=SC1091
source ./_dm-helper.sh 2>/dev/null || source _dm-helper.sh 2>/dev/null

source_dmscripts_configs

if configs_are_different; then
    echo "$(date): configs are different" >>"$DM_CONFIG_DIFF_LOGFILE"
    sleep 1
fi

main() {
    wifi_list=$(nmcli -f SSID,SECURITY,RATE,BARS,SIGNAL device wifi list | tail -n +2)

    selected_line=$(echo "$wifi_list" | ${MENU} "Select Wifi  :")
    selected_ssid=$(echo "$selected_line" | awk -F'  ' '{print $1}' | xargs)

    pass=$(printf '%s' "" | ${MENU} "Enter Password 󰟵 :")

    if [ -n "$pass" ]; then
        nmcli device wifi connect "$selected_ssid" password "$pass"
    else
        nmcli device wifi connect "$selected_ssid"
    fi

    if ping -q -c 2 -W 2 google.com >/dev/null; then
        echo "Your internet is working :)"
    else
        echo "Your internet is not working :("
    fi
}

MENU="$(get_menu_program "$@")"
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main

